/**
 * @fileoverview gRPC-Web generated client stub for chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.2
// source: chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as chat_pb from './chat_pb'; // proto import: "chat.proto"


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/SendMessage',
    grpcWeb.MethodType.UNARY,
    chat_pb.ChatMessage,
    chat_pb.Empty,
    (request: chat_pb.ChatMessage) => {
      return request.serializeBinary();
    },
    chat_pb.Empty.deserializeBinary
  );

  sendMessage(
    request: chat_pb.ChatMessage,
    metadata?: grpcWeb.Metadata | null): Promise<chat_pb.Empty>;

  sendMessage(
    request: chat_pb.ChatMessage,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.Empty) => void): grpcWeb.ClientReadableStream<chat_pb.Empty>;

  sendMessage(
    request: chat_pb.ChatMessage,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.ChatService/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.ChatService/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorChatStream = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/ChatStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    chat_pb.ChatStreamRequest,
    chat_pb.ChatMessage,
    (request: chat_pb.ChatStreamRequest) => {
      return request.serializeBinary();
    },
    chat_pb.ChatMessage.deserializeBinary
  );

  chatStream(
    request: chat_pb.ChatStreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<chat_pb.ChatMessage> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chat.ChatService/ChatStream',
      request,
      metadata || {},
      this.methodDescriptorChatStream);
  }

}

