// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/server.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           bool                   `protobuf:"varint,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_api_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerResponse) GetRun() bool {
	if x != nil {
		return x.Run
	}
	return false
}

var File_api_proto_server_proto protoreflect.FileDescriptor

const file_api_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/server.proto\x1a\x1bgoogle/protobuf/empty.proto\"\"\n" +
	"\x0eServerResponse\x12\x10\n" +
	"\x03run\x18\x01 \x01(\bR\x03run2@\n" +
	"\rServerService\x12/\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x0f.ServerResponseB\x16Z\x14api/pb/server;serverb\x06proto3"

var (
	file_api_proto_server_proto_rawDescOnce sync.Once
	file_api_proto_server_proto_rawDescData []byte
)

func file_api_proto_server_proto_rawDescGZIP() []byte {
	file_api_proto_server_proto_rawDescOnce.Do(func() {
		file_api_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_server_proto_rawDesc), len(file_api_proto_server_proto_rawDesc)))
	})
	return file_api_proto_server_proto_rawDescData
}

var file_api_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_server_proto_goTypes = []any{
	(*ServerResponse)(nil), // 0: ServerResponse
	(*emptypb.Empty)(nil),  // 1: google.protobuf.Empty
}
var file_api_proto_server_proto_depIdxs = []int32{
	1, // 0: ServerService.Ping:input_type -> google.protobuf.Empty
	0, // 1: ServerService.Ping:output_type -> ServerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_server_proto_init() }
func file_api_proto_server_proto_init() {
	if File_api_proto_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_server_proto_rawDesc), len(file_api_proto_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_server_proto_goTypes,
		DependencyIndexes: file_api_proto_server_proto_depIdxs,
		MessageInfos:      file_api_proto_server_proto_msgTypes,
	}.Build()
	File_api_proto_server_proto = out.File
	file_api_proto_server_proto_goTypes = nil
	file_api_proto_server_proto_depIdxs = nil
}
